import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* Top border */}
        <div style={{
          height: "4px",
          background: "linear-gradient(90deg, transparent, var(--color-gold), var(--color-red), var(--color-gold), transparent)"
        }} />

        {/* Nav */}
        <nav style={{
          borderBottom: "1px solid var(--color-border)",
          padding: "16px 40px",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
        }}>
          <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
            <span style={{ fontSize: "28px" }}>⚔️</span>
            <span style={{
              fontSize: "20px",
              letterSpacing: "0.15em",
              textTransform: "uppercase" as const,
              color: "var(--color-gold)",
              fontWeight: "bold",
            }}>
             <a href={`/`}>Kevin's DnD Helper</a>
            </span>
          </div>
          <div style={{ display: "flex", gap: "32px" }}>
            {["Campaigns", "Monsters"].map(item => (
              <a key={item} href={`/${item.toLowerCase()}`} style={{
                color: "var(--color-text-dim)",
                textDecoration: "none",
                letterSpacing: "0.08em",
                fontSize: "14px",
                textTransform: "uppercase" as const,
              }}>
                {item}
              </a>
            ))}
          </div>
        </nav>

        {/* Page content */}
        {children}

        {/* Bottom border */}
        <div style={{
          height: "4px",
          background: "linear-gradient(90deg, transparent, var(--color-red), var(--color-gold), var(--color-red), transparent)",
        }} />
      </body>
    </html>
  )
}
